language: php

matrix:
  include:
    - php: 5.3
    - php: 5.4
      dist: trusty
      sudo: required
    - php: 5.5
      dist: trusty
      sudo: required
    - php: 5.6
      dist: trusty
      sudo: required
    - php: 7.0
      dist: trusty
      sudo: required
    - php: hhvm
      dist: trusty
      sudo: required

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master

install:
    - composer install

script:
  - phpunit --debug -c phpunit.xml.dist

env:
  global:
    - secure: NIp6EaQ5PuW82Vz4VRQEKWQyvBiyyr328VGy6ssfYVcHscTxmWj/c6ItQva1YhRG+rkkqaxk5/12dV3DrXlseXXuXsTlSUUhccUpmQZwQksQaKd/WCCJGO5E6N0TWc7xZTKTarL6Ez9K8pbhJHfCLMKNAij0U+RGohUWGp6vjQI=
    - secure: vrh60ZzJQdIjhFdX/PxYyk7w7b7rBq/xX365Ixyav/h7tJ8IfpkNiDlXNZkF0/6GnzWNPm66lQiBs+BXpwR5DzMK11c+5M7Yz9MP/XSCFzUOd52aj/wmAVsbFj3LSpcJL7BBOOWIVM5kAr6+KU/0ggwGzrUJ0Msv4oOfcDEjObs=
