language: php

branches:
  only:
    - master
    - 1.x

matrix:
  include:
    - php: 5.3
      dist: precise
      env: LEGACY_HTTP=true # Don't install Guzzle to test PHP53HttpClient
    - php: 5.6
      dist: xenial
      sudo: required
    - php: 7.2
      dist: bionic
      sudo: required
    - php: 7.2
      dist: bionic
      sudo: required
      env: GUZZLE_6=true # Run the CTS against Guzzle 6
    - php: 7.2
      dist: bionic
      sudo: required
      env: GUZZLE_7=true # Run the CTS against Guzzle 7
    - php: 7.3
      dist: bionic
      sudo: required
    - php: 7.3
      dist: bionic
      sudo: required
      env: GUZZLE_6=true # Run the CTS against Guzzle 6
    - php: 7.3
      dist: bionic
      sudo: required
      env: GUZZLE_7=true # Run the CTS against Guzzle 7
    - php: 7.4
      dist: bionic
      sudo: required
    - php: 7.4
      dist: bionic
      sudo: required
      env: GUZZLE_6=true # Run the CTS against Guzzle 6
    - php: 7.4
      dist: bionic
      sudo: required
      env: GUZZLE_7=true # Run the CTS against Guzzle 7

    - php: hhvm
      dist: trusty
      sudo: required
    - php: nightly
      dist: trusty
      sudo: required

  allow_failures:
    - php: hhvm
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install
  - if [ $GUZZLE_6 == "true" ]; then composer require guzzlehttp/guzzle:^6.5 ; fi
  - if [ $GUZZLE_7 == "true" ]; then composer require guzzlehttp/guzzle:~7 ; fi

before_script:
  - wget https://alg.li/algolia-keys && chmod +x algolia-keys

script:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [[ ! "$TRAVIS_PULL_REQUEST_SLUG" =~ ^algolia\/ ]]; then eval $(./algolia-keys export) && php vendor/bin/phpunit -v --testsuite Unit,Definition,Community; else php vendor/bin/phpunit -v; fi
  - vendor/bin/php-cs-fixer fix -v --dry-run
  - php tests/tests-no-composer.php

